config/routes.rb
Rails.application.routes.draw do

  resources :enquiries

  resources :enquiries, path: "contact" do 
    collection do
      get "thanks"
    end
  end

  resources :static_pages
  root "static_pages#home"
  match "/support", to: "static_pages#support", via: "get"

  resources :services

end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController

  # GET /enquiries/new
  def index
    @enquiry = Enquiry.new
  end

  # POST /enquiries
  def create
    @enquiry = Enquiry.new(enquiry_params)

    if @enquiry.save
      redirect_to thanks_enquiries_path, notice: 'Enquiry was successfully created.'
    else
      render :new
    end
  end
  private
    # Only allow a trusted parameter "white list" through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :company, :phone, :email, :body)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :sidebar
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
    @service = Service.find(params[:id])
    @services = Service.all
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  private

    def sidebar
      @ip_cctv_services = Service.where(service_type:"IP CCTV")
      @rapid_repair_services = Service.where(service_type:"Rapid Deployment")
      @access_control_services = Service.where(service_type: "Access Control") 
      @solutions_services = Service.where(service_type: "Solutions") 
      @services_services = Service.where(service_type: "Services")  
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:title, :body, :service_type, :sub_service,)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: [:show, :edit, :update, :destroy]

  # GET /static_pages
  # GET /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1
  # GET /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages
  # POST /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to @static_page, notice: 'Static page was successfully created.' }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1
  # PATCH/PUT /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to @static_page, notice: 'Static page was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1
  # DELETE /static_pages/1.json
  def destroy
    @static_page.destroy
    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: 'Static page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def static_page_params
      params.require(:static_page).permit(:home)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/enquiries/_form.html.haml
.enquiries_form
  = form_for @enquiry do |f|
    - if @enquiry.errors.any?
      #error_explanation
        %h2
          = pluralize(@enquiry.errors.count, "error")
          prohibited this enquiry from being saved:
        %ul
          - @enquiry.errors.full_messages.each do |message|
            %li= message
    .field
      = f.label :name, 'name *'
      %br/
      = f.text_field :name
    .field
      = f.label :company
      %br/
      = f.text_field :company
    .field
      = f.label :phone
      %br/
      = f.text_field :phone
    .field
      = f.label :email, 'Email *'
      %br/
      = f.text_field :email
    .field
      = f.label :body, 'Your enquiry'
      %br/
      = f.text_area :body
    .submit_button
      = f.submit"Send"

app/views/enquiries/index.html.haml
.content.clearfix
  .enquiries.split_8.column  
    %h1 Contact Us
    %p If you have any questions then plese do not hesitate in contacting us
    .find-us
      #map-canvas
    %ul 
      %li 
        %h2 Address
      %li CSI Solution Ltd.
      %li 33a Whiffler Road
      %li Norwich
      %li Norfolk
      %li NR3 2AW
      %li 
        %h2 Tel
      %li 0843 2891559
      %li 
        %h2 Email
      %li= link_to "sales@csi-solution.co.uk", ''
      %li 
        %p
      %li Alternatively use this form below to get in touch and we will get back to you shortly

    = render 'enquiries/form'
  .split_2.column
    = render 'layouts/sidebar'

app/views/enquiries/thanks.html.haml
%h1 thanks

app/views/layouts/_body.html.haml
- if @service.sub_service == false
  .service_body.split_7.column
    = @service.body.html_safe
- else
  .service_body.split_10.column
    = @service.body.html_safe

app/views/layouts/_footer.html.haml
.content
	.footer_main
		%ul
			%li 
				%h2 Recommended
			%li= link_to "IP CCTV", root_path
			%li= link_to "Rapid Deployment", root_path
			%li= link_to "Access Control", root_path
			%li= link_to "RDS9", root_path
		%ul
			%li 
				%h2 Services
			%li= link_to "Maintenance", root_path
			%li= link_to "Consultation", root_path
			%li= link_to "Solutions", root_path
			%li= link_to "Support", root_path
		%ul
			%li 
				%h2 Products
			%li= link_to "Cameras", root_path
			%li= link_to "Bollards and Barriers", root_path
			%li= link_to "DVRs", root_path
			%li= link_to "Software", root_path
			%li= link_to "Wireless", root_path
		%ul.single_buffer
			%li= link_to "Control Room Solutions", root_path
			%li= link_to "Rooms", root_path
			%li= link_to "Migration", root_path
			%li= link_to "Short Term", root_path
		%ul
			%li 
				%h2 Company
			%li= link_to "Contact Us", root_path
			%li= link_to "About", root_path
			%li= link_to "Home", root_path
		.address_block
			%p CSI Solution Ltd.<br>33a Whiffler Road<br>Norwich<br>Norfolk<br>NR3 2AW
	.footer_low
		%ul.left_foot
			%li &copy 2013 CSI Solution Ltd. All Rights Reserved 
		%ul.mid_foot
			%li Tel: 0843 289 1559 | Fax: 01603 483111 | sales@csi-solution.co.uk
		%ul.right_foot
			%li= link_to "CD2 Solutions", 'http://www.cd2solutions.co.uk' 

app/views/layouts/_header.html.haml
.content 
  .head_container
    .header_logo
    .float_links
      = link_to "Home", root_path
      = link_to "Contact us", enquiries_path
    .nav
      %ul.head_menu
        - Service.where(sub_service: false).where(service_type: "IP CCTV").each do |service|
          %li
            %h3= link_to service.title, service 
            %ul
              - Service.where(sub_service: true).where(service_type: "IP CCTV").each do |service|
                %li
                  %p= link_to service.title, service
      %ul.head_menu
        - Service.where(sub_service: false).where(service_type: "Rapid Deployment").each do |service|
          %li
            %h3= link_to service.title, service 
            %ul
              - Service.where(sub_service: true).where(service_type: "Rapid Deployment").each do |service|
                %li
                  %p= link_to service.title, service
      %ul.head_menu
        - Service.where(sub_service: false).where(service_type: "Access Control").each do |service|
          %li
            %h3= link_to service.title, service 
            %ul
              - Service.where(sub_service: true).where(service_type: "Access Control").each do |service|
                %li
                  %p= link_to service.title, service
      %ul.head_menu
        - Service.where(sub_service: false).where(service_type: "Solutions").each do |service|
          %li
            %h3= link_to service.title, service 
            %ul
              - Service.where(sub_service: true).where(service_type: "Solutions").each do |service|
                %li
                  %p= link_to service.title, service
      %ul.head_menu
        - Service.where(sub_service: false).where(service_type: "Services").each do |service|
          %li
            %h3= link_to service.title, service 
            %ul
              - Service.where(sub_service: true).where(service_type: "Services").each do |service|
                %li  
                  %p= link_to service.title, service
      %ul.head_menu
        - Service.where(sub_service: false).where(service_type: "Support").each do |service|
          %li
            %h3= link_to service.title, service 

app/views/layouts/_mainservice.html.haml
%ul.main_service_sidebar.split_3.column
  - if  @service.title == "IP CCTV"
    - Service.where(sub_service: true).where(service_type: "IP CCTV").each do |service|
      %li
        %h3= link_to service.title, service
        = truncate(service.body.html_safe, :length => 61, :escape => false)

  - elsif @service.title == "Rapid Deployment"
    - Service.where(sub_service: true).where(service_type: "Rapid Deployment").each do |service|
      %li
        %h3= link_to service.title, service
  - elsif @service.title == "Access Control"
    - Service.where(sub_service: true).where(service_type: "Access Control").each do |service|
      %li
        %h3= link_to service.title, service
  - elsif @service.title == "Solutions"
    - Service.where(sub_service: true).where(service_type: "Solutions").each do |service|
      %li
        %h3= link_to service.title, service
  - elsif @service.title == "Services"
    - Service.where(sub_service: true).where(service_type: "Services").each do |service|
      %li
        %h3= link_to service.title, service

app/views/layouts/_service_header.html.haml
- if  @service.title == "IP CCTV"
  - Service.where(sub_service: false).where(service_type: "IP CCTV").each do |service|
    = image_tag("ipcctv.jpg")
- elsif @service.title == "Rapid Deployment"
  - Service.where(sub_service: false).where(service_type: "Rapid Deployment").each do |service|
    = image_tag("webbanners_0015_rapidde.jpg")
- elsif @service.title == "Access Control"
  - Service.where(sub_service: false).where(service_type: "Access Control").each do |service|
    = image_tag("webbanners_0011_Access.jpg")
- elsif @service.title == "Solutions"
  - Service.where(sub_service: false).where(service_type: "Solutions").each do |service|
    = image_tag("webbanners_0006_Solutions.jpg")
- elsif @service.title == "Services"
  - Service.where(sub_service: false).where(service_type: "Services").each do |service|
    = image_tag("webbanners_0003_serv.jpg")
- elsif @service.title == "Support"
  - Service.where(sub_service: false).where(service_type: "Support").each do |service|
    = image_tag("webbanners_0003_serv.jpg")

app/views/layouts/_sidebar.html.haml
.sidebar
  %ul
    - Service.where(sub_service: false).where(service_type: "IP CCTV").each do |service|
      %li
        %h3= link_to service.title, service 
        - Service.where(sub_service: true).where(service_type: "IP CCTV").each do |service|
          %p= link_to service.title, service
  %ul
    - Service.where(sub_service: false).where(service_type: "Rapid Deployment").each do |service|
      %li
        %h3= link_to service.title, service 
        - Service.where(sub_service: true).where(service_type: "Rapid Deployment").each do |service|
          %p= link_to service.title, service
  %ul
    - Service.where(sub_service: false).where(service_type: "Access Control").each do |service|
      %li
        %h3= link_to service.title, service 
        - Service.where(sub_service: true).where(service_type: "Access Control").each do |service|
          %p= link_to service.title, service
  %ul
    - Service.where(sub_service: false).where(service_type: "Solutions").each do |service|
      %li
        %h3= link_to service.title, service 
        - Service.where(sub_service: true).where(service_type: "Solutions").each do |service|
          %p= link_to service.title, service
  %ul
    - Service.where(sub_service: false).where(service_type: "Services").each do |service|
      %li
        %h3= link_to service.title, service 
        - Service.where(sub_service: true).where(service_type: "Services").each do |service|
          %p= link_to service.title, service
  %ul
    - Service.where(sub_service: false).where(service_type: "Support").each do |service|
      %li
        %h3= link_to service.title, service 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Csisolution
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
    %script{:src => "http://maps.googleapis.com/maps/api/js?sensor=false"}
    %script{:src => "//use.typekit.net/fgj6smy.js"}
    :javascript
      try{Typekit.load();}catch(e){}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .general_wrap 
      = render "layouts/header"
      = yield
      = render "layouts/footer"

app/views/services/_form.html.haml
= form_for(@service) do |f|
  - if @service.errors.any?
    #error_explanation
      %h2
        = pluralize(@service.errors.count, "error")
        prohibited this service from being saved:
      %ul
        - @service.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .field
    = f.select :service_type, ["IP CCTV", "Rapid Deployment", "Access Control", "Solutions", "Services", "Support"]
  .field
    = f.label :sub_service, 'Tick to create as a main Service:'
    = f.check_box :sub_service
  .field
    = f.label :side_image, 'image for main services side menu'
    = f.file_field :side_image
  .actions
    = f.submit

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.haml
.content.clearfix
  .services
    %h1 Services
    =image_tag("webbanner.jpg")
    .column.split_4
      %h2 An Approach you can trust
      %p We pride ourselves on the level of service and the quality advice we provide for our clientele. Our team of consultants have gained extensive experience specialising in all aspects of CCTV survey, design, installations and commissioning. Consistently working to the highest standards and specifications with the latest and established technology.

      %p CSI Solution prides itself on its reputation by maintaining all the appropriate security industry and associated engineering standards on all its previous and on-going work within the Railway Industry, Housing Associations, Management Companies, Local Authorities and the Private Sector. Being an expert on CCTV, and an independent CCTV engineering consultant we can ensure a fair and reasonable service and maintenance contract is in put place to ensure your fully commissioned system is maintained appropriately and effectively. This can be a small fraction of the standard proposals made by some CCTV system installers.

    .column.split_8
      %h2 Some considerations when implementing a CCTV system

      %p Choosing the right CCTV Camera system - Due to the increasing number of CCTV related products on the market it can be quite intimidating to know which product or system to choose. Whether you want to design and install a single access point or complex CCTV digital recording system with multiple users across many sites, our CCTV Consultants can help you decipher your requirements to enable you to achieve a system that is tailored to meet your individual business needs. So with all complexities of designing and implementing a CCTV security or safety camera system we are here to help point you in the right direction and ultimately help you choose the best, most econmic and effective system.

      %p CCTV systems are normally outside the knowledge base of most organisations and this means there is a lot of uncertainty as to whether or not it is the right solution. Even once it is decided that a CCTV system could aid or provide a solution quite often a badly designed/installed systems will fail to live up to the original intentions of the purchaser. What we have found is that a well-planned and implemented CCTV systems normally expands fairly fast over a period of years as the added value becomes clear and the CCTV system becomes integrated into the everyday operation of the business.

      %ul
        %li Long/Short term CCTV solution Hire.
        %li CCTV Bespoke system design and manufacture.
        %li Alternative power supply systems for remote locations including Fuel-cell, Petrol generators, Solar panel and 12Vdc Battery Back-up.
        %li System integration providing a platform for seamless total security management.
        %li Demographic statistics, which can be made part of your POS system.
        %li Data-storage compliance advice with regard to the The Data Protection Act 1998 / 2003, Freedom of Information Act 2000, Crime and Disorder Act 1998.
        %li Control room planning, design &amp; implementation

    .column.split_4.service_list
      %ul
        - @services.each do |service|
          %li 
            =image_tag("fpcsi.png")
            %h2= service.title.titleize
            .body_text
              = truncate(service.body.html_safe, :length => 400, :escape => false)
    .column.split_2
      = render 'layouts/sidebar'

app/views/services/new.html.haml
.content
	%h1 New service
	= render 'form'
	= link_to 'Back', services_path

app/views/services/show.html.haml
.content.clearfix
  .service.column
    %p#notice= notice
    .service_cont
      .column.split_8
        .service_banner.split_10.column
          =render 'layouts/service_header'
        .service_title
          %h1
            = @service.title.html_safe
          = render 'layouts/body'
        = render 'layouts/mainservice'
      .split_2.column
        = render 'layouts/sidebar'
      

app/views/static_pages/home.html.haml
.content
  .home.clearfix
    %h1 Welcome to CSI Solution Ltd
    %h2 Specialists in IP CCTV
    .video
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "506", :src => "https://www.youtube.com/embed/JvsxaQ7k_BA", :width => "850"}
    .home_text.clearfix
      .body_text.split_7.column
        %h3 About CSI Solution
        %p CSI Solution Ltd is a company founded on the idea of Combined Security Intergration. At the forefront of technology, we will protect you and your business whatever your circumstance. With Rapid Deployment Cameras, we can mobilise complete CCTV coverage to your site in a very short space of time and through intruder and access control, we ensure you are protected into the future.
        %h3 Our Promise
        %p CSI Solution has a combined 30 years combined experience in the field of security camera solutions and access control, we have taken a fresh innovative approach to the security industry to meet the ever growing demands you face of protecting your staff and premises.
        %p With our dedicated team of Engineers and friendly administration staff we can provide you with professional help and advice on installation, maintenance and support anywhere in the United Kingdom.
      .split_3.column.right_img
        =image_tag("fpcsi.png")